### ISSUE TITLE
Downloads now via AWS

### ISSUE THREAD

**Issue by jkrauska** [mikenowak/docker-nessus#4]
The method used to get a TOKEN to do a download no longer works.

I was able to manually download rpm from here:
https://www.tenable.com/downloads/nessus
(Note, it's now on 7.0.2 and es7 image is a bit down the page)

Not sure how to trivially redo this...

**Comment by mikenowak** [comment]
Thank you for reporting this @jkrauska, I am going to investigate this and revert back.
