### ISSUE TITLE
Issue with mounting persistent volume

### ISSUE THREAD

**Issue by ankursawhneyatmecs** [mikenowak/docker-nessus#6]
I had issue while mounting persistent volume to "/opt/nessus". Though I didn't got any error, the host folder overwrote "/opt/nessus" on container causing following error - 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./opt/nessus/sbin/nessus-service\": stat ./opt/nessus/sbin/nessus-service: no such file or directory": unknown

So, I removed the mount point and am making do without it currently. Any help here would be appreciated !!

**Comment by mikenowak** [comment]
Hi @ankursawhneyatmecs, I need more info in order to help you out.

For starters - can you tell how are you exactly starting your container, can you share the exact command please?

**Comment by ankursawhneyatmecs** [comment]
@mikenowak Thank you ! Got the issue resolved. Just needed to shift the VOLUME command to file end as otherwise, the host context overwrote /opt/nessus
COMMAND I AM USING : sudo docker run --name nessus1 -d -p 8834:8834 -v `pwd`:/opt/nessus nessus:tailmount
